name: Build and Release

on:
  push:
    branches: [ main ]
  workflow_dispatch:  # Allows manual triggering

jobs:
  create-release:
    runs-on: ubuntu-latest
    outputs:
      upload_url: ${{ steps.create_release.outputs.upload_url }}
      version: ${{ steps.get_version.outputs.version }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Set up Python for version extraction
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      
      - name: Get version from setup.py
        id: get_version
        run: |
          # Extract version from setup.py using Python
          VERSION=$(python -c "import re; print(re.search(r'version=[\"\'](.*?)[\"\']', open('setup.py').read()).group(1))")
          echo "Version detected from setup.py: $VERSION"
          echo "version=$VERSION" >> $GITHUB_OUTPUT
      
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ steps.get_version.outputs.version }}
          release_name: Release v${{ steps.get_version.outputs.version }}
          draft: true
          prerelease: false
          body: |
            ## CaughtUP Release v${{ steps.get_version.outputs.version }}
        
            Automated build from the main branch.
            
            ### Downloads
            - Windows: CaughtUP-Windows-${{ steps.get_version.outputs.version }}.zip
            - macOS: CaughtUP-macOS-${{ steps.get_version.outputs.version }}.pkg
            
            ### macOS Installation Instructions
            1. Download the .pkg installer
            2. Double-click to launch the installer
            3. Follow the installation wizard
            4. After installation, find "Open CaughtUP First Time.command" in Applications
            5. Right-click on this file and select "Open"
            6. When the security warning appears, click "Open"
            
            After first launch, you can open CaughtUP normally.
            
            *This is an automatically generated draft release. Please add release notes before publishing.*

  build-windows:
    needs: create-release
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          cache: 'pip'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller
      
      - name: Modify spec file to remove logs directory dependency
        run: |
          (Get-Content CaughtUP.spec) -replace "'logs', 'logs'", "'build_resources', 'build_resources'" | Set-Content CaughtUP.spec
      
      - name: Build Windows executable
        run: |
          pyinstaller CaughtUP.spec
      
      - name: Zip Windows artifact
        run: |
          Compress-Archive -Path dist\CaughtUP.exe -DestinationPath CaughtUP-Windows.zip
      
      - name: Upload Windows artifact to release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.create-release.outputs.upload_url }}
          asset_path: ./CaughtUP-Windows.zip
          asset_name: CaughtUP-Windows-${{ needs.create-release.outputs.version }}.zip
          asset_content_type: application/zip

  build-macos:
    needs: create-release
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          cache: 'pip'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller
      
      - name: Modify spec file to remove logs directory dependency
        run: |
          sed -i '' "s/'logs', 'logs'/'build_resources', 'build_resources'/g" CaughtUP.spec
      
      - name: Build macOS app
        run: |
          pyinstaller CaughtUP.spec
      
      - name: Prepare installer resources
        run: |
          # Create directories
          mkdir -p pkg_resources
          mkdir -p scripts
          
          # Copy the postinstall script
          cp installer/macos/postinstall scripts/
          chmod +x scripts/postinstall
          
          # Copy the welcome text and update version
          sed "s/VERSION/${{ needs.create-release.outputs.version }}/g" installer/macos/welcome.txt > pkg_resources/welcome.txt
          
          # Copy distribution.xml
          cp installer/macos/distribution.xml ./
      
      - name: Create PKG installer
        run: |
          # Build component package
          pkgbuild --root dist/ \
                  --identifier com.vidaldl.caughtup \
                  --version ${{ needs.create-release.outputs.version }} \
                  --install-location /Applications \
                  --scripts scripts \
                  component.pkg
          
          # Build distribution package
          productbuild --distribution distribution.xml \
                      --resources pkg_resources \
                      CaughtUP-macOS.pkg
      
      - name: Upload macOS installer
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.create-release.outputs.upload_url }}
          asset_path: ./CaughtUP-macOS.pkg
          asset_name: CaughtUP-macOS-${{ needs.create-release.outputs.version }}.pkg
          asset_content_type: application/x-newton-compatible-pkg